import Script from "next/script";
import "./globals.css";
import Header from "./(components)/Header";
import { Space_Mono } from "next/font/google";
import ReduxProvider from "@/provider/redux/ReduxProvider";
import { NextAuthProvider } from "@/provider/google/NextAuthProvider";
import Footer from "./(components)/Footer";
import { Outfit } from "next/font/google";
const outfit = Outfit({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-outfit",
});
const spaceMono = Space_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-space-mono",
  weight: "400",
});
export const metadata = {
  title: "Sky-Shop",
  description: "Generated by Sky",
};

export default function RootLayout({ children }) {
  return (
    <ReduxProvider>
      <NextAuthProvider>
        <html lang="en" className={`${spaceMono.variable} ${outfit.variable}`}>
          <body className={outfit.className}>
            <Header />
            {children}
            <Footer />
          </body>
        </html>
        <Script src="https://checkout.razorpay.com/v1/checkout.js" />
      </NextAuthProvider>
    </ReduxProvider>
  );
}
